In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/drug200.csv')
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [2]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [3]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [4]:
x=df.iloc[:,0:5]
x.head()

Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043

In [5]:
y=pd.get_dummies(df.iloc[:,5:]).values
y

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1,

In [6]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=12)

In [7]:
x.shape, y.shape

((200, 5), (200, 5))

In [8]:
xtrain.shape,xtest.shape

((160, 5), (40, 5))

In [9]:
df['BP'].unique()

array(['HIGH', 'LOW', 'NORMAL'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
xtrain['Sex'] = le.fit_transform(xtrain['Sex'])
xtrain['Sex']
xtest['Sex'] = le.transform(xtest['Sex'])
xtest['Sex']
xtrain['BP'] = le.fit_transform(xtrain['BP'])
xtrain['BP']
xtest['BP'] = le.transform(xtest['BP'])
xtest['BP']
xtrain['Cholesterol'] = le.fit_transform(xtrain['Cholesterol'])
xtrain['Cholesterol']
xtest['Cholesterol'] = le.transform(xtest['Cholesterol'])
xtest['Cholesterol']

23     0
182    1
172    1
21     0
63     1
11     1
61     1
32     1
164    1
7      0
95     1
173    1
132    1
120    0
98     1
138    1
31     0
16     1
181    0
85     0
185    1
166    0
101    0
129    0
113    1
51     1
167    0
88     1
108    1
136    0
29     0
183    1
152    1
93     1
189    1
139    0
179    0
55     0
1      0
5      0
Name: Cholesterol, dtype: int64

In [12]:
xtrain

Age  Sex  BP  Cholesterol  Na_to_K
77    26    0   0            1   19.161
47    68    1   1            0   10.291
94    56    1   1            0   15.015
14    50    0   2            0   12.703
41    58    0   0            1   14.239
..   ...  ...  ..          ...      ...
3     28    0   2            0    7.798
130   70    0   2            0   20.489
134   42    0   0            0   21.036
155   49    1   1            0   10.537
75    26    1   1            1   20.909

[160 rows x 5 columns]

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(5,input_dim=5,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(5,activation='softmax'))

In [14]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 30        
                                                                 
 dense_1 (Dense)             (None, 64)                384       
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 32)                1056      
                                                                 
 dense_4 (Dense)             (None, 5)                 165       
                                                                 
Total params: 3,715
Trainable params: 3,715
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.fit(xtrain,ytrain,epochs=19,batch_size=5,validation_data=(xtest,ytest))

Epoch 1/19
32/32 [==============================] - 2s 11ms/step - loss: 1.3527 - accuracy: 0.4750 - val_loss: 1.1313 - val_accuracy: 0.6000
Epoch 2/19
32/32 [==============================] - 0s 3ms/step - loss: 1.0997 - accuracy: 0.5875 - val_loss: 0.9968 - val_accuracy: 0.6500
Epoch 3/19
32/32 [==============================] - 0s 3ms/step - loss: 1.0541 - accuracy: 0.5875 - val_loss: 0.9849 - val_accuracy: 0.6500
Epoch 4/19
32/32 [==============================] - 0s 3ms/step - loss: 1.0169 - accuracy: 0.5875 - val_loss: 0.9875 - val_accuracy: 0.6500
Epoch 5/19
32/32 [==============================] - 0s 4ms/step - loss: 1.0097 - accuracy: 0.5813 - val_loss: 0.9844 - val_accuracy: 0.6500
Epoch 6/19
32/32 [==============================] - 0s 4ms/step - loss: 0.9910 - accuracy: 0.5938 - val_loss: 0.9747 - val_accuracy: 0.6750
Epoch 7/19
32/32 [==============================] - 0s 3ms/step - loss: 0.9840 - accuracy: 0.5875 - val_loss: 0.9705 - val_accuracy: 0.6750
Epoch 8/19
32/32 [=

In [17]:
v=np.random.rand(10,5)
v

array([[0.00724331, 0.47526568, 0.89374927, 0.62121278, 0.33902871],
       [0.82537132, 0.93494105, 0.33707386, 0.60674379, 0.97569973],
       [0.1435424 , 0.03679599, 0.75331254, 0.13003326, 0.31112494],
       [0.03932711, 0.60505957, 0.02957241, 0.02422345, 0.53915763],
       [0.24948223, 0.79339038, 0.90274156, 0.50756399, 0.75894902],
       [0.62447762, 0.91361044, 0.18920059, 0.76497852, 0.27776588],
       [0.12033058, 0.39493969, 0.96707213, 0.14512693, 0.91999939],
       [0.28240971, 0.81592423, 0.48440353, 0.70754439, 0.41313533],
       [0.33066145, 0.2145221 , 0.29978081, 0.59366596, 0.20521066],
       [0.35867497, 0.76239261, 0.66455304, 0.71972933, 0.61051265]])

In [27]:
z=model.predict(v)
z=z.round(decimals=0)
z=z.astype(int)
z

1/1 [==============================] - 0s 22ms/step


array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]])

In [44]:
class_labels = np.argmax(z, axis=1)
class_labels

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])